#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

install() {
  packages_install pass

  if [[ ${OSTYPE} =~ ^darwin ]]; then
    packages_install pass-otp
  elif command -v apt-get >/dev/null 2>&1; then
    packages_install pass-extension-otp
  fi
}

credentials() {
}
