#!/usr/bin/env bash

set -o nounset -o pipefail -o errexit

script_dir() {
  local FILE_SOURCE="${BASH_SOURCE[0]}"

  if [[ -L ${FILE_SOURCE} ]]; then
    dirname "$(readlink "${FILE_SOURCE}")"
  else
    (
      cd "$(dirname "${FILE_SOURCE}")" && pwd
    )
  fi
}

clean() {
  rm -rf "${HOME}/.molotov-aws" "${HOME}/.myclirc"
}

install_mycli() {
  echo "[main]
multi_line = True
auto_vertical_output = True
row_limit = 100
log_level = ERROR
" >"${HOME}/.myclirc"
}

install() {
  if command -v brew >/dev/null 2>&1; then
    brew install mycli protobuf
    brew install --cask tunnelblick
  fi

  go install "github.com/molotovtv/go-aws@master"
  go install "github.com/molotovtv/go-i18n/cmd/i18n-analyzer@master"
  go install "github.com/GoogleCloudPlatform/cloudsql-proxy/cmd/cloud_sql_proxy@latest"

  install_mycli

  dns_allow "aws"
  dns_allow "datadog"

  docker_start
}
